import { Schema, model, Document } from "mongoose";

//Role entity with fields: name (WAITER, BARTENDER, MANAGER, SUPERVISOR)
//Role can have multiple users, but for simplicity we will not implement the relationship in the database, we will handle it in the application logic
//added createdAt field to all entities for better tracking and sorting

export interface IRole extends Document {
  //added id to make it sequential instead of auto generated by MongoDB, this will make it easier to manage and reference roles in the application logic
  id: number;
  createdAt: Date;
  name: string; //WAITER, BARTEDNER, MANAGER, SUPERVISOR

  //many to many relationship with User
  users: string[]; //array of user ids
}

const roleSchema = new Schema<IRole>(
  {
    id: { type: Number, required: true, unique: true },
    name: { type: String, required: true, unique: true },
    users: [{ type: Schema.Types.ObjectId, ref: "User" }],
  },
  { timestamps: true },
);

export const Role = model<IRole>("Role", roleSchema);
