### Create menu item
POST http://localhost:3000/api/menu-items
Content-Type: application/json

{
  "name": "Espresso Martini",
  "price": 11.5,
  "section": "COCKTAIL",
  "available": true
}

### Get all menu items
GET http://localhost:3000/api/menu-items

### Get one menu item
GET http://localhost:3000/api/menu-items/{{menuItemId}}

### Delete a menu item
DELETE http://localhost:3000/api/menu-items/{{menuItemId}}


### Create role
POST http://localhost:3000/api/roles
Content-Type: application/json

{
  "name": "BARTENDER"
}

### Get all roles
GET http://localhost:3000/api/roles

### Update role
PUT http://localhost:3000/api/roles/{{roleId}}
Content-Type: application/json

{
  "name": "MANAGER"
}
