### Create Order
POST http://localhost:3000/api/orders
Content-Type: application/json

{
  "tabId": 1,
  "userId": 1
}

### Get all orders
GET http://localhost:3000/api/orders

### Get order by id
GET http://localhost:3000/api/orders/1

### Update order
PATCH http://localhost:3000/api/orders/1
Content-Type: application/json

{
  "tabId": 2
}


### Add item to order
POST http://localhost:3000/api/orders/1/items
Content-Type: application/json

{
  "menuItemId": 1,
  "quantity": 5
}

### Get all items in order
GET http://localhost:3000/api/orders/1/items

### Update item in order
PUT http://localhost:3000/api/orders/1/items/1
Content-Type: application/json

{
  "menuItemId": 1,
  "quantity": 3
}

### Delete item from order
DELETE http://localhost:3000/api/orders/1/items/1


### Pay order manager logged in
POST http://localhost:3000/api/orders/1/pay
Content-Type: application/json

{
  "amount": 10.50,
  "paymentMethod": "CASH"
}

### Pay order as waiter logged in
POST http://localhost:3000/api/orders/1/pay
Content-Type: application/json

{
  "amount": 57,
  "paymentMethod": "CARD"
}
