### Create menu item
POST http://localhost:3000/api/menu-items
Content-Type: application/json

{
  "name": "Espresso Martini",
  "price": 11.5,
  "section": "COCKTAIL",
  "available": true
}

### Get all menu items
GET http://localhost:3000/api/menu-items

### Delete a menu item
DELETE http://localhost:3000/api/menu-items/{{menuItemId}}


