### Create menu item
POST http://localhost:3000/api/menu-items
Content-Type: application/json

{
  "name": "Pornstar Martini",
  "price": 13.5,
  "section": "COCKTAIL"
}

### Get all menu items
GET http://localhost:3000/api/menu-items

### Delete a menu item
DELETE http://localhost:3000/api/menu-items/{{menuItemId}}


