### Create a new table
POST http://localhost:3000/api/tabs
Content-Type: application/json

{
  "tableNumber": "TABLE 5",
  "tableStatus": "open"
}

### Get all tables
GET http://localhost:3000/api/tabs
Content-Type: application/json

### Get a specific table
GET http://localhost:3000/api/tabs/1

### Update a table
PUT http://localhost:3000/api/tabs/1
Content-Type: application/json

{
  "tableNumber": "TABLE 1"
}


### Delete a table
DELETE http://localhost:3000/api/tabs/3


### Change the table status
PATCH http://localhost:3000/api/tabs/1/status
Content-Type: application/json

{
  "tableStatus": "free"
}